name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Go
      id: go
      uses: actions/setup-go@v5
      with:
        go-version: stable
        check-latest: true

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Test
      run: |
        go test -race ./... && go vet ./...

    - name: Build
      uses: goreleaser/goreleaser-action@v6
      with:
        args: build --snapshot --clean

    - name: Release
      uses: goreleaser/goreleaser-action@v6
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      with:
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
