name: Go

on:
  - push
  - pull_request

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ^1.22
      id: go

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Test
      run: |
        go test -race ./... && go vet ./...

    - name: Build
      run: |
        GOARCH=amd64 CGO_ENABLED=0 go build -o ayano-amd64 -v .
        GOARCH=arm64 CGO_ENABLED=0 go build -o ayano-arm64 -v .

    - name: Deploy - Create Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        draft: false
        files: |
          ayano-amd64
          ayano-arm64
        prerelease: false
